#include "HW4.h"

// C++ program generated by SLK from file: HW4


int main()
{
       string full_name ;
       string address ;
       string phone_number ;
       string email_address_1 ;
       string email_address_2 ;
       int num_hours ;
       string statement ;
       string satisfied ;
       int try_again ;
       int chances ;
       
       do
       {
              cout << "What is your name?" << endl;
              getline(cin, full_name);
              cout << "What is your home address?" << endl;
              getline(cin, address);
              cout << "What is your phone number?" << endl;
              getline(cin, phone_number);
              try_again = 3;
              cout << "What is your email address?" << endl;
              getline(cin, email_address_1);
              cout << "For verification, please re-enter your email address" << endl;
              getline(cin, email_address_2);
              try_again = try_again - 1;
              
              while ((email_address_1 != email_address_2 ) && ( try_again > 0 ))
              {
                     cout << "What is your email address?" << endl;
                     getline(cin, email_address_1);
                     cout << "For verification, please re-enter your email address" << endl;
                     getline(cin, email_address_2);
                     try_again = try_again - 1;
                     
              }
              
              if (try_again >= 0 )
              {
                     ;
                     chances = 5;
                     cout << "How many hours a week are you available to work? (Between 1 - 40 hours)" << endl;
                     cin >> num_hours;
                     cin.ignore();
                     chances = chances - 1;
                     
                     while (((num_hours <= 0 ) || ( num_hours > 40 ) && ( chances > 0 )))
                     {
                            cout << "I'm sorry... Please re-enter" << endl;
                            cin >> num_hours;
                            cin.ignore();
                            chances = chances - 1;
                            
                     }
                     
                     if (chances != 0 )
                     {
                            ;
                            cout << "Why do you want this job?" << endl;
                            getline(cin, statement);
                            cout << "Are you satisfied with what you have entered? (Y or N)" << endl;
                            cin >> satisfied;
                            cin.ignore();
                            for(int i=satisfied.length(); i >= 0; satisfied[i] = tolower(satisfied[i]), --i);
                            
                            while ((satisfied != "y") && ( satisfied != "n"))
                            {
                                   cout << "Please re-enter..." << endl;
                                   cin >> satisfied;
                                   cin.ignore();
                                   
                            }
                            
                     }
                     
              }
              
       } while (satisfied == "n"); 
       
       if (satisfied == "y")
       {
              ;
              cout << "Name: " << ' ' << full_name << endl;
              cout << "Address: " << ' ' << address << endl;
              cout << "Phone Number: " << ' ' << phone_number << endl;
              cout << "Email Address: " << ' ' << email_address_1 << endl;
              cout << "Number of hours you have indicated you are available: " << ' ' << num_hours << ' ' << " hours" << endl;
              cout << "Why you want this job: " << ' ' << statement << endl;
              
       }
       
       return 0;
} 
